<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $productos = [
            [
                'codigo' => '7790895000011',
                'nombre' => 'Leche La Serenísima entera 1L',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 6,
                'precio_compra_unitario' => 1250.00,
                'precio_compra_bulto' => 7500.00,
                'precio_venta_unitario' => 1600.00,
            ],
            [
                'codigo' => '7790070410014',
                'nombre' => 'Yerba Mate Taragüi 1kg',
                'cantidad_unidades' => 48,
                'cantidad_bultos' => 4,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 12,
                'precio_compra_unitario' => 3200.00,
                'precio_compra_bulto' => 38400.00,
                'precio_venta_unitario' => 4000.00,
            ],
            [
                'codigo' => '7791290000219',
                'nombre' => 'Aceite Natura Girasol 900ml',
                'cantidad_unidades' => 72,
                'cantidad_bultos' => 12,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 6,
                'precio_compra_unitario' => 2800.00,
                'precio_compra_bulto' => 16800.00,
                'precio_venta_unitario' => 3500.00,
            ],
            [
                'codigo' => '7790070410015',
                'nombre' => 'Harina 0000 Blancaflor 1kg',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1800.00,
                'precio_compra_bulto' => 18000.00,
                'precio_venta_unitario' => 2200.00,
            ],
            [
                'codigo' => '7790070410016',
                'nombre' => 'Azúcar Ledesma 1kg',
                'cantidad_unidades' => 80,
                'cantidad_bultos' => 8,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1600.00,
                'precio_compra_bulto' => 16000.00,
                'precio_venta_unitario' => 2000.00,
            ],
            [
                'codigo' => '7790070410017',
                'nombre' => 'Arroz Gallo Oro 1kg',
                'cantidad_unidades' => 90,
                'cantidad_bultos' => 9,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1900.00,
                'precio_compra_bulto' => 19000.00,
                'precio_venta_unitario' => 2300.00,
            ],
            [
                'codigo' => '7790070410018',
                'nombre' => 'Fideos Matarazzo Spaghetti 500g',
                'cantidad_unidades' => 120,
                'cantidad_bultos' => 12,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1100.00,
                'precio_compra_bulto' => 11000.00,
                'precio_venta_unitario' => 1400.00,
            ],
            [
                'codigo' => '7790070410019',
                'nombre' => 'Salsa de Tomate La Campagnola 520g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1500.00,
                'precio_compra_bulto' => 15000.00,
                'precio_venta_unitario' => 1800.00,
            ],
            [
                'codigo' => '7790070410222',
                'nombre' => 'Galletitas Oreo 117g',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2000.00,
                'precio_compra_bulto' => 20000.00,
                'precio_venta_unitario' => 2500.00,
            ],
            [
                'codigo' => '7790070410021',
                'nombre' => 'Pan Lactal Bimbo 600g',
                'cantidad_unidades' => 40,
                'cantidad_bultos' => 4,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2700.00,
            ],
            [
                'codigo' => '7790070410022',
                'nombre' => 'Levadura Levex 50g',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 800.00,
                'precio_compra_bulto' => 8000.00,
                'precio_venta_unitario' => 1000.00,
            ],
            [
                'codigo' => '7790070410023',
                'nombre' => 'Manteca Sancor 200g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2500.00,
                'precio_compra_bulto' => 25000.00,
                'precio_venta_unitario' => 3000.00,
            ],
            [
                'codigo' => '7790070410024',
                'nombre' => 'Queso Cremoso La Paulina 1kg',
                'cantidad_unidades' => 30,
                'cantidad_bultos' => 3,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 8500.00,
                'precio_compra_bulto' => 85000.00,
                'precio_venta_unitario' => 10000.00,
            ],
            [
                'codigo' => '7790070410025',
                'nombre' => 'Huevos Blancos Dúo x12',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2700.00,
            ],
            [
                'codigo' => '7790070410026',
                'nombre' => 'Café La Virginia 500g',
                'cantidad_unidades' => 40,
                'cantidad_bultos' => 4,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 5000.00,
                'precio_compra_bulto' => 50000.00,
                'precio_venta_unitario' => 6000.00,
            ],
            [
                'codigo' => '7790070410027',
                'nombre' => 'Yerba Mate Rosamonte Selección Especial 1kg',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 12,
                'precio_compra_unitario' => 8000.00,
                'precio_compra_bulto' => 96000.00,
                'precio_venta_unitario' => 9500.00,
            ],
            [
                'codigo' => '7791290000019',
                'nombre' => 'Aceite Cocinero Girasol 900ml',
                'cantidad_unidades' => 72,
                'cantidad_bultos' => 12,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 6,
                'precio_compra_unitario' => 2800.00,
                'precio_compra_bulto' => 16800.00,
                'precio_venta_unitario' => 3500.00,
            ],
            [
                'codigo' => '7790070410028',
                'nombre' => 'Harina 0000 Blancaflor 1kg',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1800.00,
                'precio_compra_bulto' => 18000.00,
                'precio_venta_unitario' => 2200.00,
            ],
            [
                'codigo' => '7790070410029',
                'nombre' => 'Azúcar Ledesma 1kg',
                'cantidad_unidades' => 80,
                'cantidad_bultos' => 8,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1600.00,
                'precio_compra_bulto' => 16000.00,
                'precio_venta_unitario' => 2000.00,
            ],
            [
                'codigo' => '7790070410030',
                'nombre' => 'Arroz Gallo Oro 1kg',
                'cantidad_unidades' => 90,
                'cantidad_bultos' => 9,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1900.00,
                'precio_compra_bulto' => 19000.00,
                'precio_venta_unitario' => 2300.00,
            ],
            [
                'codigo' => '7790070410031',
                'nombre' => 'Fideos Matarazzo Spaghetti 500g',
                'cantidad_unidades' => 120,
                'cantidad_bultos' => 12,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1100.00,
                'precio_compra_bulto' => 11000.00,
                'precio_venta_unitario' => 1400.00,
            ],
            [
                'codigo' => '7790070410032',
                'nombre' => 'Salsa de Tomate La Campagnola 520g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1500.00,
                'precio_compra_bulto' => 15000.00,
                'precio_venta_unitario' => 1800.00,
            ],
            [
                'codigo' => '7790070410033',
                'nombre' => 'Galletitas Oreo 117g',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2000.00,
                'precio_compra_bulto' => 20000.00,
                'precio_venta_unitario' => 2500.00,
            ],
            [
                'codigo' => '7790070410034',
                'nombre' => 'Pan Lactal Bimbo 600g',
                'cantidad_unidades' => 40,
                'cantidad_bultos' => 4,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2700.00,
            ],
            [
                'codigo' => '7790070410035',
                'nombre' => 'Levadura Levex 50g',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 800.00,
                'precio_compra_bulto' => 8000.00,
                'precio_venta_unitario' => 1000.00,
            ],
            [
                'codigo' => '7790070410036',
                'nombre' => 'Manteca Sancor 200g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2500.00,
                'precio_compra_bulto' => 25000.00,
                'precio_venta_unitario' => 3000.00,
            ],
            [
                'codigo' => '7790070410037',
                'nombre' => 'Queso Cremoso La Paulina 1kg',
                'cantidad_unidades' => 30,
                'cantidad_bultos' => 3,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 7000.00,
                'precio_compra_bulto' => 70000.00,
                'precio_venta_unitario' => 8500.00,
            ],
            [
                'codigo' => '7790070410038',
                'nombre' => 'Leche La Serenísima Entera 1L',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1800.00,
                'precio_compra_bulto' => 18000.00,
                'precio_venta_unitario' => 2200.00,
            ],
            [
                'codigo' => '7790070410039',
                'nombre' => 'Huevos Blancos Doca x12',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2700.00,
            ],
            [
                'codigo' => '7790070410040',
                'nombre' => 'Café La Morenita 500g',
                'cantidad_unidades' => 40,
                'cantidad_bultos' => 4,
                'bultos_min_aviso' => 1,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 3500.00,
                'precio_compra_bulto' => 35000.00,
                'precio_venta_unitario' => 4200.00,
            ],
            [
                'codigo' => '7790070410020',
                'nombre' => 'Manteca La Serenísima 200g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2400.00,
                'precio_compra_bulto' => 24000.00,
                'precio_venta_unitario' => 2900.00,
            ],
            [
                'codigo' => '77900704230028',
                'nombre' => "Mayonesa Hellmann's 800g",
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 3500.00,
                'precio_compra_bulto' => 35000.00,
                'precio_venta_unitario' => 4200.00,
            ],
            [
                'codigo' => '7790344070613',
                'nombre' => 'Detergente Líquido Ayudín 900ml',
                'cantidad_unidades' => 80,
                'cantidad_bultos' => 8,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2600.00,
            ],
            [
                'codigo' => '7790070210040',
                'nombre' => 'Té Lipton 250g',
                'cantidad_unidades' => 90,
                'cantidad_bultos' => 9,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1800.00,
                'precio_compra_bulto' => 18000.00,
                'precio_venta_unitario' => 2200.00,
            ],
            [
                'codigo' => '7790031165107',
                'nombre' => 'Galletitas Chiquilin x400g',
                'cantidad_unidades' => 75,
                'cantidad_bultos' => 7,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1700.00,
                'precio_compra_bulto' => 17000.00,
                'precio_venta_unitario' => 2100.00,
            ],
            [
                'codigo' => '7790070410057',
                'nombre' => 'Cereal Nesquik 300g',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2500.00,
                'precio_compra_bulto' => 25000.00,
                'precio_venta_unitario' => 3000.00,
            ],
            [
                'codigo' => '7790070410065',
                'nombre' => 'Café instantáneo Nescafé 170g',
                'cantidad_unidades' => 70,
                'cantidad_bultos' => 7,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2800.00,
                'precio_compra_bulto' => 28000.00,
                'precio_venta_unitario' => 3300.00,
            ],
            [
                'codigo' => '7790344071078',
                'nombre' => 'Champú Head & Shoulders 400ml',
                'cantidad_unidades' => 80,
                'cantidad_bultos' => 8,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 3500.00,
                'precio_compra_bulto' => 35000.00,
                'precio_venta_unitario' => 4200.00,
            ],
            [
                'codigo' => '7790070410073',
                'nombre' => 'Aspirina 500mg x20',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1200.00,
                'precio_compra_bulto' => 12000.00,
                'precio_venta_unitario' => 1500.00,
            ],
            [
                'codigo' => '7790070410081',
                'nombre' => 'Papel Higiénico Elite x4',
                'cantidad_unidades' => 90,
                'cantidad_bultos' => 9,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1500.00,
                'precio_compra_bulto' => 15000.00,
                'precio_venta_unitario' => 1900.00,
            ],
            [
                'codigo' => '7790070410099',
                'nombre' => 'Papel Higiénico Negra Nena x8',
                'cantidad_unidades' => 85,
                'cantidad_bultos' => 8,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1900.00,
                'precio_compra_bulto' => 19000.00,
                'precio_venta_unitario' => 2300.00,
            ],
            [
                'codigo' => '7790070410102',
                'nombre' => 'Limpia Vidrios Ayudín 500ml',
                'cantidad_unidades' => 60,
                'cantidad_bultos' => 6,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 1100.00,
                'precio_compra_bulto' => 11000.00,
                'precio_venta_unitario' => 1400.00,
            ],
            [
                'codigo' => '7790070410119',
                'nombre' => 'Jabón en Barra Palmolive x4',
                'cantidad_unidades' => 100,
                'cantidad_bultos' => 10,
                'bultos_min_aviso' => 4,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 800.00,
                'precio_compra_bulto' => 8000.00,
                'precio_venta_unitario' => 1000.00,
            ],
            [
                'codigo' => '7790070410127',
                'nombre' => 'Desodorante Nivea x150ml',
                'cantidad_unidades' => 70,
                'cantidad_bultos' => 7,
                'bultos_min_aviso' => 3,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2200.00,
                'precio_compra_bulto' => 22000.00,
                'precio_venta_unitario' => 2700.00,
            ],
            [
                'codigo' => '7790070410135',
                'nombre' => 'Cuidado Facial Garnier x100ml',
                'cantidad_unidades' => 50,
                'cantidad_bultos' => 5,
                'bultos_min_aviso' => 2,
                'cantidad_por_bulto' => 10,
                'precio_compra_unitario' => 2500.00,
                'precio_compra_bulto' => 25000.00,
                'precio_venta_unitario' => 3000.00,
            ]
        ];

        // --- INICIO CORRECCIÓN DE REPETIDOS ---
        $nombres = [];
        $codigos = [];
        foreach ($productos as $k => &$prod) {
            // Corregir nombres repetidos
            $nombreOriginal = $prod['nombre'];
            $nombre = $nombreOriginal;
            $i = 2;
            while (in_array($nombre, $nombres)) {
                $nombre = $nombreOriginal . ' (Variante ' . $i . ')';
                $i++;
            }
            $prod['nombre'] = $nombre;
            $nombres[] = $nombre;
            // Corregir códigos repetidos
            $codigoOriginal = $prod['codigo'];
            $codigo = $codigoOriginal;
            $j = 1;
            while (in_array($codigo, $codigos)) {
                // Cambia el último dígito o agrega uno nuevo
                if (is_numeric($codigo)) {
                    $codigo = substr($codigoOriginal, 0, -1) . $j;
                } else {
                    $codigo = $codigoOriginal . $j;
                }
                $j++;
            }
            $prod['codigo'] = $codigo;
            $codigos[] = $codigo;
        }
        // --- FIN CORRECCIÓN DE REPETIDOS ---

        foreach ($productos as $producto) {
            Product::create($producto);
        }
    }
}
